### ISSUE TITLE
change mysql port

### ISSUE THREAD

**Issue by qusthuang** [goodrain/rainbond-install#105]
for safety , I prefer to change port for mysql，for example 13306.
I change port in two file "install/salt/db/mysql/files/my.cnf" and "rainbond.yaml.default" . 
[client]
--
4 | port		= 13306

But when excuting command setup install ,the  port in file "/opt/rainbond/db/mysql/files/my.cnf" is 3306(even deleted). Is there somthing wrong?

**Comment by ysicing** [comment]
# 未安装
需要修改三处:
```bash
#  rainbond-install/rainbond.yaml.default
    68	    port: 13306
#  rainbond-install/install/salt/db/mysql/files/my.cnf
     4	port		= 13306
    15	port		= 13306
```

# 已安装
```
dc-compose stop
cclear
rm -rf /opt/rainbond/data/rbd-db/

# /srv/pillar/rainbond.yaml.default
    68	    port: 13306
# /srv/salt/db/mysql/files/my.cnf
     4	port		= 13306
    15	port		= 13306
```

@qusthuang  应该没有修改 mysqld 监听端口吧

**Comment by qusthuang** [comment]
ok,thanks
