### ISSUE TITLE
certificate signed by unknown authority

### ISSUE THREAD

**Issue by mskmkt0704** [goodrain/rainbond-install#119]
please complete the following information:

 - OS:  Centos  7.4.1708
 - Kernel Version: 3.10.0-693.5.2.el7.x86_64
 - Rainbond Version: 3.6
 - Environment: Local-machine

![image](https://user-images.githubusercontent.com/10786748/43505403-6857c336-9599-11e8-910b-db244891dbce.png)

**Comment by ysicing** [comment]
@mskmkt0704  手动执行一下看看能否push镜像。

**Comment by mskmkt0704** [comment]
一样的错误, 看起来是goodrain.me的证书没有被信任, 这个证书的ca放在什么位置呢, 我可以试着手动加入信任

**Comment by ysicing** [comment]
goodrain.me这个证书是两年前生成的证书了，自签证书,未保留ca证书。

**Comment by ysicing** [comment]
你可以重新执行安装，检查一下docker的配置，或者参考 [insecure registry](https://docs.docker.com/registry/insecure/#troubleshoot-insecure-registry), goodrain.me配置在rbd-lb配置的

**Comment by mskmkt0704** [comment]
更正一下 我的云帮版本是3.6.1, 错误可能和centos的版本有关. 
问题解决, 我先关掉这个issue了.
