### ISSUE TITLE
grctl: command not found

### ISSUE THREAD

**Issue by xsser** [goodrain/rainbond-install#152]
update domain status ok
./setup.sh: line 759: grctl: command not found
./setup.sh: line 759: grctl: command not found
./setup.sh: line 759: grctl: command not found
./setup.sh: line 759: grctl: command not found
./setup.sh: line 759: grctl: command not found
./setup.sh: line 759: grctl: command not found

**Comment by ysicing** [comment]
怎么安装的？
最后集群有报错吗？

**Comment by xsser** [comment]
> 怎么安装的？
> 最后集群有报错吗？

我完全按照官方文档操作的  版本也是7.3 1161的，直接install 提示minion  没有reponse，我就重新安装了下还是提示这个，最后重新安装了下salt-master那些   就出现这个grctl的问题了。。。。。。。
我全部按照官方的 怎么还会出现问题。。。

**Comment by xsser** [comment]
Salt request timed out. The master is not responding. You may need to run your command with `--async` in order to bypass the congested event bus. With `--async`, the CLI tool will print the job id (jid) and exit immediately without listening for responses. You can then use `salt-run jobs.lookup_jid` to look up the results of the job in the job cache later.

**Comment by xsser** [comment]
不管是重启也好 还是怎么的
Minion did not return. [No response]

还是报错这个。。。

**Comment by ysicing** [comment]
你手动安装salt有问题吗? [手动安装saltstack服务来排查saltstack服务](http://t.goodrain.com/t/salt-salt/455)

**Comment by ysicing** [comment]
最好贴下salt的相关日志，/var/log/salt

**Comment by ysicing** [comment]
这个问题得检查$PATH 是否添加了/usr/local/bin
