### ISSUE TITLE
install Failed salt

### ISSUE THREAD

**Issue by 4021019** [goodrain/rainbond-install#47]
--- Installing salt ... --- 
 FAILED  Failed to install salt!

**Comment by zhouyq** [comment]
cat rainbond-install/logs/install_salt.log  for more information

please run  ./install  again

**Comment by 4021019** [comment]
Downloading packages:
warning: /var/cache/yum/x86_64/7/saltstack/packages/python-jinja2-2.7.2-2.el7.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
Retrieving key from https://mirrors.ustc.edu.cn/salt/yum/redhat/7/x86_64/archive/2017.7.4/SALTSTACK-GPG-KEY.pub


The GPG keys listed for the "SaltStack archive/2017.7.4 Release Channel for RHEL/CentOS 7" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.


 Failing package is: python-jinja2-2.7.2-2.el7.noarch
 GPG Keys are configured as: https://mirrors.ustc.edu.cn/salt/yum/redhat/7/x86_64/archive/2017.7.4/SALTSTACK-GPG-KEY.pub

^[[1;31m * ERROR^[[0m: Failed to run install_centos_stable()!!!

直接 yum install python-jinja2 --nogpgcheck

**Comment by ysicing** [comment]
fixed #52
