### ISSUE TITLE
Rainbond integrated customized docker, Please uninstall it first. 

### ISSUE THREAD

**Issue by dingyong666** [goodrain/rainbond-install#64]
--- Check system environment... --- 
 FAILED  Rainbond integrated customized docker, Please uninstall it first. 

Quit rainbond install program.

**Comment by ysicing** [comment]
目前要求环境只能是我们定制版本的docker

**Comment by zhouyq** [comment]
报这个问题的原因主要是你系统中已经有docker，如果是在安装云帮过程中终止，再安装也会有这个问题，如果是前者请卸载docker，如果是后者，请使用dev分支代码安装。这个问题在dev分支已经解决，最近两天合并到master

**Comment by ysicing** [comment]
已经修复。
