### ISSUE TITLE
使用安装脚本，在make_domain步骤出错

### ISSUE THREAD

**Issue by leocd** [goodrain/rainbond-install#72]
在分配泛解析域名这一步报错退出
master分支和dev分支均存在此问题，请问如何解决？
![12](https://user-images.githubusercontent.com/7478643/39398505-5911f44a-4afe-11e8-8ec8-9f7bf93643ff.gif)

**Comment by zhouyq** [comment]
从截图的stdout来看，是注册域名时临时解析失败，你可以重新执行 ./setup.sh install 跑一下试试。

后续我们会增强该步骤的容错。

感谢反馈问题

**Comment by ysicing** [comment]
@leocd  可以提供一下系统，内核版本么？

**Comment by leocd** [comment]
@ysicing 系统 centos 7.4.1708  内核 3.10.0-693.21.1.el7.x86_64

**Comment by leocd** [comment]
@zhouyq 你好，重试了20多次，每次都是在这一步失败。

**Comment by leocd** [comment]
安装的机器是一台内网机，没有分配公网地址。dns已按照帮助文档设置成114.114.114.114，ip为静态ip。

**Comment by ysicing** [comment]
@leocd  报错都是这样是吧，你执行脚本后，看dns是否发生了改变

**Comment by leocd** [comment]
@ysicing 是的，每次报错都是这个信息，执行脚本后dns还是114.114.114.114，也尝试过修改/etc/hosts解析www.cloudxns.net，但依然是这个错误。

**Comment by leocd** [comment]
@ysicing dns和转发没有问题
![12](https://user-images.githubusercontent.com/7478643/39402923-2ab4b748-4ba0-11e8-91d7-ca245647626c.gif)

**Comment by leocd** [comment]
@ysicing 通过docker run -it debian:stretch-slim /bin/bash进入容器执行apt-get update，提示W: Failed to fetch http://deb.debian.org/debian/dists/stretch/InRelease  Temporary failure resolving 'deb.debian.org'来看，是容器内无法联网，确认宿主机的ipv4.ip_forward已设置为1。

**Comment by leocd** [comment]
@ysicing 好的，谢谢，我用ubuntu做宿主机再试装看看。

**Comment by ysicing** [comment]
@leocd  请问机器是物理机还是虚拟机，如果是虚拟机是基于vmware，virtualbox还是其他，可否告知一下
