### ISSUE TITLE
安装脚本错误

### ISSUE THREAD

**Issue by zhangjianweibj** [goodrain/rainbond-install#96]
![image](https://user-images.githubusercontent.com/18585129/41327822-8a1d4842-6ef7-11e8-9154-76dbb371b9bb.png)

unbuntu16系统安装，一直出这个错误

**Comment by ysicing** [comment]
哪个版本v3.5还是v3.6

**Comment by zhangjianweibj** [comment]
V3.5的 @ysicing

**Comment by zhangjianweibj** [comment]
手动安装加入public key可以解决了。但是又出现了这个问题。

![image](https://user-images.githubusercontent.com/18585129/41328220-90f457bc-6ef9-11e8-892a-07b206ac6e94.png)

**Comment by ysicing** [comment]
@zhangjianweibj  机器什么配置，重新执行一下安装命令

**Comment by zhangjianweibj** [comment]
8核  16G内存  100G硬盘

**Comment by ysicing** [comment]
目前临时解决方法：
```
systemctl restart salt-minion.service
salt-key -L
salt-key -A
salt-key -L
# 结果如下
Accepted Keys:
manage01
Denied Keys:
Unaccepted Keys:
Rejected Keys:
# 重新执行安装命令
./setup.sh install
```

**Comment by ysicing** [comment]
```
systemctl unmask docker.service
systemctl unmask docker.socket
systemctl start docker.service
```

**Comment by like-inspur** [comment]
@ysicing 我之前卸载了docker，apt-get remove gr-docker-engine，现在发现docker就没装

**Comment by like-inspur** [comment]
![image](https://user-images.githubusercontent.com/18571465/41328923-29512370-6efd-11e8-8a4b-76dcaa998c89.png)

**Comment by ysicing** [comment]
@like-inspur  重新执行安装

**Comment by ysicing** [comment]
@zhangjianweibj  @like-inspur  可以了么

**Comment by like-inspur** [comment]
![image](https://user-images.githubusercontent.com/18571465/41330329-6d043000-6f05-11e8-9ede-fb05fe88cd0f.png)
执行了./setup.sh install，还是一样的错误

**Comment by ysicing** [comment]
就是将docker卸载后，安装docker这步安装失败是吗？我这边看看能否复现一下 @like-inspur

**Comment by like-inspur** [comment]
@ysicing 是的，你那复现了吗

**Comment by ysicing** [comment]
@like-inspur  已经复现，现在正在解决

**Comment by ysicing** [comment]
@like-inspur  临时解决方法，可以先安装docker，然后重新执行安装命令 
```
apt-get install -y gr-docker-engine
```

**Comment by like-inspur** [comment]
![image](https://user-images.githubusercontent.com/18571465/41333693-4d4021ec-6f15-11e8-91c9-dc5ccbbae876.png)

**Comment by ysicing** [comment]
确定docker版本 是`1.12.6 fbecf51`
```
# docker version
docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   fbecf51
 Built:        Fri Jun  8 04:33:13 2018
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   fbecf51
 Built:        Fri Jun  8 04:33:13 2018
 OS/Arch:      linux/amd64
# check
cat /srv/pillar/rainbond.sls | grep 1.12.6
  version: 1.12.6,fbecf51
```
如果不是，修改`/srv/pillar/rainbond.sls` L15的version信息

**Comment by like-inspur** [comment]
![image](https://user-images.githubusercontent.com/18571465/41333969-4f7cf056-6f16-11e8-816b-9a94c4183429.png)

**Comment by ysicing** [comment]
然后安装还报这个吗？

**Comment by zhangjianweibj** [comment]
![image](https://user-images.githubusercontent.com/18585129/41334078-ca093848-6f16-11e8-972e-6b27646c108f.png)

都试了N遍了，还是不行。你随便找个干净的机器试试效果。

**Comment by ysicing** [comment]
@zhangjianweibj 
我这边也测试了也没遇到安装docker后，没有复现无法安装这个。
第一个问题是docker没有卸载干净导致docker没有安装卸载可以使用`apt-get purge gr-docker-engine`
你可以手动执行`salt "*" state.sls docker `看看
如果还有问题，使用`./setup.sh dev`

**Comment by zhangjianweibj** [comment]
![image](https://user-images.githubusercontent.com/18585129/41343192-85eee774-6f30-11e8-8311-72613f1470ca.png)
@ysicing 3q，多次安装终于成功了一次。但是监控没有数据啊。应用是官方自带的demo。

**Comment by ysicing** [comment]
@zhangjianweibj  性能分析插件安装了吗。如果安装插件了，需要重启一下应用

**Comment by zhangjianweibj** [comment]
![image](https://user-images.githubusercontent.com/18585129/41344795-9079ac3e-6f34-11e8-9a9f-45abe774d629.png)
插件安装了也开启了，服务也重启了。就是没有数据

**Comment by ysicing** [comment]
@zhangjianweibj  
更新一下node的配置`/opt/rainbond/scripts/start-node.sh`中的`NODE_OPTS`的值新增如下
```
--statsd.mapping-config=/opt/rainbond/etc/rbd-node/mapper.yml
```
示例：
```
NODE_OPTS=" --statsd.mapping-config=/opt/rainbond/etc/rbd-node/mapper.yml   --log-level=debug --kube-conf=/opt/rainbond/etc/kubernetes/kubecfg/admin.kubeconfig --nodeid-file=/opt/rainbond/etc/rbd-node/node_host_uuid.conf --static-task-path=/opt/rainbond/etc/rbd-node/tasks/ --etcd=http://127.0.0.1:2379   --hostIP=10.10.10.235 --run-mode master --noderule manage,compute"
```
更新完，重启一下node
```
systemctl restart node
```
刷新一下监控页即可

**Comment by zhangjianweibj** [comment]
3q，终于可以了。功能可以完善完善。监控信息太少了，还少告警模块。针对不同的服务，完全可以定制不同的exporter进行。

**Comment by ysicing** [comment]
告警模块已经列在todolist里了。具体可以和barnettZQG 讨论
/cc @barnettZQG

**Comment by barnettZQG** [comment]
@ghangjianweibj 目前应用控制台只呈现应用业务级监控，对于应用开发者和使用者来说，吞吐和响应时间是最直接的应用状态指标。 你说的资源监控方面在资源管理后台呈现。
